sudo: required

services:
  - docker

before_install:
  - docker pull debian:sid-slim

script:
  - docker run -v $PWD:/mnt/ghoaepp debian:sid-slim /bin/bash -c "cd /mnt/ghoaepp/utils; ./travis-dependencies.sh; ./travis-build.sh"
